# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-08 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('keyword', models.CharField(blank=True, default='', max_length=256)),
                ('creator', models.CharField(default='', editable=False, max_length=256, verbose_name='创建人')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modifier', models.CharField(default='', editable=False, max_length=256, verbose_name='修改人')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('is_valid', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name', 'type'],
            },
        ),
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('keyword', models.CharField(blank=True, default='', max_length=256)),
                ('creator', models.CharField(default='', editable=False, max_length=256, verbose_name='创建人')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modifier', models.CharField(default='', editable=False, max_length=256, verbose_name='修改人')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('is_valid', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('keyword', models.CharField(blank=True, default='', max_length=256)),
                ('creator', models.CharField(default='', editable=False, max_length=256, verbose_name='创建人')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modifier', models.CharField(default='', editable=False, max_length=256, verbose_name='修改人')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('is_valid', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CaseVsStep2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='', editable=False, max_length=256, verbose_name='创建人')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modifier', models.CharField(default='', editable=False, max_length=256, verbose_name='修改人')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('is_valid', models.BooleanField(default=True)),
                ('order', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Case')),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('keyword', models.CharField(blank=True, default='', max_length=256)),
                ('creator', models.CharField(default='', editable=False, max_length=256, verbose_name='创建人')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modifier', models.CharField(default='', editable=False, max_length=256, verbose_name='修改人')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('is_valid', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('keyword', models.CharField(blank=True, default='', max_length=256)),
                ('creator', models.CharField(default='', editable=False, max_length=256, verbose_name='创建人')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modifier', models.CharField(default='', editable=False, max_length=256, verbose_name='修改人')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('is_valid', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('keyword', models.CharField(blank=True, default='', max_length=256)),
                ('creator', models.CharField(default='', editable=False, max_length=256, verbose_name='创建人')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modifier', models.CharField(default='', editable=False, max_length=256, verbose_name='修改人')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('is_valid', models.BooleanField(default=True)),
                ('timeout', models.FloatField(blank=True, null=True)),
                ('save_as', models.CharField(blank=True, max_length=256)),
                ('ui_by', models.IntegerField(choices=[(0, ''), (1, 'id'), (2, 'xpath'), (3, 'link text'), (4, 'partial link text'), (5, 'name'), (6, 'tag name'), (7, 'class name'), (8, 'css selector'), (9, 'public element'), (10, 'variable')], default=0)),
                ('ui_locator', models.TextField(blank=True)),
                ('ui_index', models.IntegerField(blank=True, null=True)),
                ('ui_base_element', models.TextField(blank=True)),
                ('ui_data', models.TextField(blank=True)),
                ('ui_special_action', models.IntegerField(choices=[(0, ''), (1, 'click'), (2, 'click_and_hold'), (3, 'context_click'), (4, 'double_click'), (5, 'release'), (6, 'move_by_offset'), (7, 'move_to_element'), (8, 'move_to_element_with_offset'), (9, 'drag_and_drop'), (10, 'drag_and_drop_by_offset'), (11, 'key_down'), (12, 'key_up'), (13, 'send_keys'), (14, 'send_keys_to_element')], default=0)),
                ('ui_alert_handle', models.IntegerField(choices=[(0, ''), (1, 'accept'), (2, 'dismiss'), (3, 'ignore')], default=0)),
                ('api_url', models.TextField(blank=True)),
                ('api_headers', models.TextField(blank=True)),
                ('api_body', models.TextField(blank=True)),
                ('api_data', models.TextField(blank=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Action')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='casevsstep2',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Step'),
        ),
        migrations.AddField(
            model_name='case',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Config'),
        ),
        migrations.AddField(
            model_name='action',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ActionType'),
        ),
        migrations.AlterUniqueTogether(
            name='casevsstep2',
            unique_together=set([('case', 'step')]),
        ),
        migrations.AlterUniqueTogether(
            name='action',
            unique_together=set([('name', 'type')]),
        ),
    ]
