# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-08 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CaseVsStep2',
            new_name='CaseVsStep',
        ),
    ]
