# Generated by Django 5.0.2 on 2024-10-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='api_response_status',
            field=models.TextField(blank=True),
        ),
    ]
