# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-10 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180408_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={},
        ),
        migrations.AlterModelOptions(
            name='casevsstep',
            options={'ordering': ['case', 'order']},
        ),
        migrations.AddField(
            model_name='step',
            name='cases',
            field=models.ManyToManyField(through='main.CaseVsStep', to='main.Case'),
        ),
    ]
