# Generated by Django 2.0.7 on 2018-09-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180921_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='db_port',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='step',
            name='db_type',
            field=models.IntegerField(choices=[(1, 'Oracle'), (2, 'MysSQL')], default=1),
        ),
    ]
