# Generated by Django 5.0.2 on 2024-10-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_step_api_response_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='error_handle',
            field=models.IntegerField(choices=[(0, '继承上级'), (1, '中止测试'), (2, '继续测试'), (3, '暂停测试'), (4, '忽略（不记录错误）')], default=0),
        ),
        migrations.AlterField(
            model_name='step',
            name='error_handle',
            field=models.IntegerField(choices=[(0, '继承上级'), (1, '中止测试'), (2, '继续测试'), (3, '暂停测试'), (4, '忽略（不记录错误）')], default=0),
        ),
        migrations.AlterField(
            model_name='suite',
            name='error_handle',
            field=models.IntegerField(choices=[(1, '中止测试'), (2, '继续测试'), (3, '暂停测试'), (4, '忽略（不记录错误）')], default=1),
        ),
    ]
