# Generated by Django 2.0.7 on 2018-09-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180925_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='db_type',
            field=models.IntegerField(choices=[(1, 'Oracle'), (2, 'MySQL')], default=1),
        ),
    ]
