# Generated by Django 5.0.2 on 2024-11-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_case_error_handle_alter_step_error_handle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='other_input',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='ui_driver_type',
            field=models.IntegerField(choices=[(1, 'Chrome'), (2, 'IE'), (3, 'FireFox'), (4, 'Edge')], default=1),
        ),
    ]
