# Generated by Django 2.0.7 on 2018-09-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180926_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='api_save',
            field=models.TextField(blank=True),
        ),
    ]
