# Generated by Django 5.0.2 on 2024-11-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_step_other_input_alter_config_ui_driver_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='other_input',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
