# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 03:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180412_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='cases',
        ),
        migrations.AddField(
            model_name='case',
            name='step',
            field=models.ManyToManyField(through='main.CaseVsStep', to='main.Step'),
        ),
        migrations.AlterField(
            model_name='case',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='case_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
            preserve_default=False,
        ),
    ]
