# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 03:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180412_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Config'),
        ),
        migrations.AlterField(
            model_name='case',
            name='modifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='case_modifier', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='step',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='step_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='step',
            name='modifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='step_modifier', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
    ]
