# Generated by Django 2.0.7 on 2018-10-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_step_api_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='api_decode',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
