# Generated by Django 5.0.2 on 2024-12-20 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_dataset_case_data_set_datasetrow_datasetcell'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datasetrow',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='datasetrow',
            name='data_set',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='column_names',
            new_name='data',
        ),
        migrations.DeleteModel(
            name='DataSetCell',
        ),
        migrations.DeleteModel(
            name='DataSetRow',
        ),
    ]
