# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 03:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180412_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={},
        ),
        migrations.AlterField(
            model_name='action',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='action_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='action',
            name='modifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='action_modifier', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='actiontype',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='action_type_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='actiontype',
            name='modifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='action_type_modifier', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='casevsstep',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='case_vs_step_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='casevsstep',
            name='modifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='case_vs_step_modifier', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='config',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='config_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='config',
            name='modifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='config_modifier', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='group',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='group_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='group',
            name='modifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='group_modifier', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
    ]
