# Generated by Django 2.0.7 on 2018-10-26 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_step_api_decode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid1, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('by', models.IntegerField(choices=[(0, ''), (1, 'id'), (2, 'xpath'), (3, 'link text'), (4, 'partial link text'), (5, 'name'), (6, 'tag name'), (7, 'class name'), (8, 'css selector'), (9, 'public element'), (10, 'variable')], default=0)),
                ('locator', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ElementGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid1, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('keyword', models.CharField(blank=True, max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('is_active', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='element_group_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='element_group_modifier', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Project')),
            ],
            options={
                'ordering': ['-modified_date'],
            },
        ),
        migrations.AddField(
            model_name='suiteresult',
            name='element_group',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='element_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ElementGroup'),
        ),
        migrations.AddField(
            model_name='suite',
            name='element_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ElementGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='element',
            unique_together={('name', 'element_group')},
        ),
    ]
