# Generated by Django 2.0.5 on 2018-05-04 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20180412_1151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='action',
            name='keyword',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.ActionType'),
        ),
        migrations.AlterField(
            model_name='actiontype',
            name='keyword',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='actiontype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='case',
            name='keyword',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='casevsstep',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Case'),
        ),
        migrations.AlterField(
            model_name='casevsstep',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Step'),
        ),
        migrations.AlterField(
            model_name='config',
            name='keyword',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='config',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='keyword',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='step',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Action'),
        ),
        migrations.AlterField(
            model_name='step',
            name='keyword',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='step',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='step',
            name='save_as',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
