# Generated by Django 2.0.7 on 2018-11-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20181026_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='suiteresult',
            name='result_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='suiteresult',
            name='result_message',
            field=models.TextField(blank=True),
        ),
    ]
