# Generated by Django 2.0.7 on 2018-11-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20181107_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='suiteresult',
            name='log_level',
            field=models.IntegerField(default=20),
        ),
    ]
