# Generated by Django 5.0.2 on 2025-01-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_dataset_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseresult',
            name='data_set',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stepresult',
            name='runtime_variables',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caseresult',
            name='config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caseresult',
            name='variable_group',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suiteresult',
            name='config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suiteresult',
            name='element_group',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suiteresult',
            name='variable_group',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
