# Generated by Django 2.0.5 on 2018-05-25 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20180504_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='is_valid',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='actiontype',
            old_name='is_valid',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='is_valid',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='config',
            old_name='is_valid',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='is_valid',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='step',
            old_name='is_valid',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='casevsstep',
            name='is_valid',
        ),
    ]
