# Generated by Django 2.0.5 on 2018-06-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20180525_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='ui_selenium_client',
            field=models.IntegerField(choices=[(1, '本地'), (2, '远程')], default=1),
        ),
        migrations.AlterField(
            model_name='casevsstep',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='casevsstep',
            unique_together=set(),
        ),
    ]
