# Generated by Django 5.0.2 on 2025-01-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_caseresult_data_set_stepresult_runtime_variables_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepresult',
            name='snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
