# Generated by Django 2.0.7 on 2018-11-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_suiteresult_log_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='ui_window_position_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='ui_window_position_y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
