# Generated by Django 2.0.7 on 2018-11-29 10:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20181127_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='expire_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='有效期'),
        ),
        migrations.AlterField(
            model_name='token',
            name='value',
            field=models.CharField(max_length=100, verbose_name='token值'),
        ),
    ]
