# Generated by Django 2.0.5 on 2018-06-04 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20180604_1644'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='casevsstep',
            unique_together={('case', 'step', 'order')},
        ),
    ]
