# Generated by Django 2.0.7 on 2018-11-29 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20181127_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='expire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 29, 9, 45, 24, 769054), null=True, verbose_name='有效期'),
        ),
    ]
