# Generated by Django 2.0.7 on 2018-12-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20181129_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stepresult',
            options={'ordering': ['end_date']},
        ),
        migrations.AddField(
            model_name='stepresult',
            name='loop_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
