# Generated by Vic on 2025-01-24 17:30

from django.db import migrations


def combine_json_fields(apps, schema_editor):
    from django.forms.models import model_to_dict
    # 获取模型
    MyModel = apps.get_model('main', 'suiteresult')
    for obj in MyModel.objects.all():
        if not obj.snapshot:
            suite = obj.suite
            _snapshot = model_to_dict(suite) if suite else None
            _snapshot['case'] = [x.pk for x in _snapshot['case']]

            _snapshot["name"] = obj.name
            _snapshot["description"] = obj.description
            _snapshot["keyword"] = obj.keyword
            _snapshot["project"] = obj.project.pk
            _snapshot["timeout"] = obj.timeout
            _snapshot["ui_step_interval"] = obj.ui_step_interval
            _snapshot["ui_get_ss"] = obj.ui_get_ss
            _snapshot["thread_count"] = obj.thread_count

            obj.snapshot = _snapshot
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_suiteresult_snapshot'),
    ]

    operations = [
        migrations.RunPython(combine_json_fields),
    ]
