# Generated by Django 2.0.5 on 2018-06-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20180604_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='ui_selenium_client',
            field=models.IntegerField(choices=[(1, '本地'), (2, '远程')], default=None, null=True),
        ),
    ]
