# Generated by Django 5.0.2 on 2025-01-24 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_update_suiteresult_snapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suiteresult',
            name='log_level',
        ),
        migrations.RemoveField(
            model_name='suiteresult',
            name='thread_count',
        ),
        migrations.RemoveField(
            model_name='suiteresult',
            name='timeout',
        ),
        migrations.RemoveField(
            model_name='suiteresult',
            name='ui_get_ss',
        ),
        migrations.RemoveField(
            model_name='suiteresult',
            name='ui_step_interval',
        ),
    ]
