# Generated by Django 2.0.7 on 2018-12-10 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20181206_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stepresult',
            options={'ordering': ['pk']},
        ),
    ]
