# Generated by Django 2.0.5 on 2018-06-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20180604_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='ui_selenium_client',
            field=models.IntegerField(choices=[(0, ''), (1, 'Selenium - 本地'), (2, 'Selenium - 远程')], default=0),
        ),
    ]
