# Generated by Django 5.0.2 on 2025-03-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_suiteresult_log_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='ui_special_action',
            field=models.IntegerField(choices=[(0, ''), (1, '鼠标 - 左键单击'), (2, '鼠标 - 左键双击'), (3, '鼠标 - 右键单击'), (4, '鼠标 - 左键点按'), (5, '鼠标 - 释放左键点按'), (6, '鼠标 - 移动到偏移点位置'), (7, '鼠标 - 移动到某元素中间'), (8, '鼠标 - 移动到某元素左上角为基准的偏移点位置'), (9, '鼠标 - 拖动某元素到另一元素上'), (10, '鼠标 - 拖动某元素到偏移点位置'), (11, '鼠标 - 滚动到偏移点位置'), (12, '鼠标 - 滚动到某元素底部'), (13, '键盘 - 按住某键'), (14, '键盘 - 释放某键'), (15, '键盘 - 发送按键（组）')], default=0),
        ),
    ]
