# Generated by Django 2.0.5 on 2018-06-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20180604_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='ui_driver',
            field=models.IntegerField(choices=[(1, 'Chrome'), (2, 'IE'), (3, 'FireFox'), (4, 'PhantomJS')], default=1),
        ),
        migrations.AddField(
            model_name='config',
            name='ui_driver_ff_profile',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='config',
            name='ui_remote_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='config',
            name='ui_remote_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='ui_window_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='ui_window_size',
            field=models.IntegerField(choices=[(1, '最大化'), (2, '自定义')], default=1),
        ),
        migrations.AddField(
            model_name='config',
            name='ui_window_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
