# Generated by Django 2.0.7 on 2018-12-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20181213_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='suiteresult',
            name='ui_step_interval',
            field=models.FloatField(default=0),
        ),
    ]
