# Generated by Django 2.0.5 on 2018-06-04 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20180604_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='ui_driver',
            new_name='ui_driver_type',
        ),
    ]
