# Generated by Django 2.0.7 on 2019-01-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_suiteresult_ui_step_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='timeout',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='ui_step_interval',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caseresult',
            name='timeout',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caseresult',
            name='ui_step_interval',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='ui_step_interval',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suiteresult',
            name='log_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suiteresult',
            name='thread_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suiteresult',
            name='timeout',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suiteresult',
            name='ui_get_ss',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='suiteresult',
            name='ui_step_interval',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
