# Generated by Django 5.0.2 on 2025-06-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_suiteresult_error_handle_caseresult_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='api_allow_redirects',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='step',
            name='api_max_redirects',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='other_input',
            field=models.TextField(blank=True),
        ),
    ]
