# Generated by Django 2.0.5 on 2018-06-05 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20180604_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='config',
        ),
        migrations.AlterField(
            model_name='config',
            name='ui_selenium_client',
            field=models.IntegerField(choices=[(1, 'Selenium - 本地'), (2, 'Selenium - 远程')], default=0),
        ),
    ]
