# Generated by Django 2.0.5 on 2018-06-05 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20180605_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actiontype',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='actiontype',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='actiontype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='actiontype',
            name='keyword',
        ),
        migrations.RemoveField(
            model_name='actiontype',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='actiontype',
            name='modifier',
        ),
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.IntegerField(choices=[(0, 'UI'), (1, 'API'), (2, 'DB')], default=1),
        ),
    ]
