# Generated by Django 2.0.7 on 2019-01-15 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20190104_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caseresult',
            old_name='result_status',
            new_name='result_state',
        ),
        migrations.RenameField(
            model_name='stepresult',
            old_name='result_status',
            new_name='result_state',
        ),
        migrations.RenameField(
            model_name='suiteresult',
            old_name='result_status',
            new_name='result_state',
        ),
    ]
