# Generated by Django 2.0.7 on 2019-01-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20190115_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='suiteresult',
            name='stop_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caseresult',
            name='result_state',
            field=models.IntegerField(blank=True, choices=[(0, '跳过'), (1, '成功'), (2, '失败'), (3, '异常'), (4, '中止')], null=True),
        ),
        migrations.AlterField(
            model_name='stepresult',
            name='result_state',
            field=models.IntegerField(blank=True, choices=[(0, '跳过'), (1, '成功'), (2, '失败'), (3, '异常'), (4, '中止')], null=True),
        ),
        migrations.AlterField(
            model_name='suiteresult',
            name='result_state',
            field=models.IntegerField(blank=True, choices=[(0, '跳过'), (1, '成功'), (2, '失败'), (3, '异常'), (4, '中止')], null=True),
        ),
    ]
