# Generated by Django 2.0.5 on 2018-06-05 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0020_auto_20180605_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('keyword', models.CharField(blank=True, default='', max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('is_active', models.BooleanField(default=True)),
                ('value', models.TextField(blank=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='variable_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('modifier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='variable_modifier', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
            ],
        ),
        migrations.CreateModel(
            name='VariableGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('keyword', models.CharField(blank=True, default='', max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('is_active', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='variable_group_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('modifier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='variable_group_modifier', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
            ],
        ),
        migrations.AddField(
            model_name='variable',
            name='variable_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.VariableGroup'),
        ),
    ]
