# Generated by Django 2.0.7 on 2019-01-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20190117_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='ui_alert_handle_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='ui_alert_handle',
            field=models.IntegerField(choices=[(1, '确定'), (2, '取消')], default=1),
        ),
    ]
