# Generated by Django 2.0.5 on 2018-06-06 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20180605_1106'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variable',
            unique_together={('name', 'variable_group')},
        ),
    ]
