# Generated by Django 2.0.7 on 2019-02-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20190130_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='ignore_error',
            field=models.BooleanField(default=False),
        ),
    ]
