# Generated by Django 2.0.5 on 2018-06-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20180606_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variable',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='keyword',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='modifier',
        ),
        migrations.AddField(
            model_name='variable',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
