# Generated by Django 2.0.7 on 2019-02-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_step_ignore_error'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='ignore_error',
        ),
        migrations.AddField(
            model_name='step',
            name='error_handle',
            field=models.IntegerField(choices=[(1, '中止测试'), (2, '继续测试'), (3, '暂停测试'), (4, '跳过步骤')], default=1),
        ),
    ]
