# Generated by Django 2.0.5 on 2018-06-11 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0023_auto_20180606_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('keyword', models.CharField(blank=True, default='', max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuiteVsCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['suite', 'order'],
            },
        ),
        migrations.RemoveField(
            model_name='group',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='group',
            name='modifier',
        ),
        migrations.AddField(
            model_name='case',
            name='variable_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.VariableGroup'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.AddField(
            model_name='suitevscase',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Case'),
        ),
        migrations.AddField(
            model_name='suitevscase',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='suite_vs_case_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='suitevscase',
            name='modifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='suite_vs_case_modifier', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AddField(
            model_name='suitevscase',
            name='suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Suite'),
        ),
        migrations.AddField(
            model_name='suite',
            name='cases',
            field=models.ManyToManyField(through='main.SuiteVsCase', to='main.Case'),
        ),
        migrations.AddField(
            model_name='suite',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Config'),
        ),
        migrations.AddField(
            model_name='suite',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='suite_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='suite',
            name='modifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='suite_modifier', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AddField(
            model_name='suite',
            name='variable_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.VariableGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='suitevscase',
            unique_together={('suite', 'case', 'order')},
        ),
    ]
