# Generated by Django 2.0.7 on 2019-03-26 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20190218_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Config'),
        ),
        migrations.AddField(
            model_name='case',
            name='error_handle',
            field=models.IntegerField(choices=[(0, ''), (1, '中止测试'), (2, '继续测试'), (3, '暂停测试'), (4, '跳过步骤')], default=0),
        ),
        migrations.AddField(
            model_name='caseresult',
            name='config',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suite',
            name='error_handle',
            field=models.IntegerField(choices=[(1, '中止测试'), (2, '继续测试'), (3, '暂停测试'), (4, '跳过步骤')], default=1),
        ),
        migrations.AlterField(
            model_name='step',
            name='error_handle',
            field=models.IntegerField(choices=[(0, ''), (1, '中止测试'), (2, '继续测试'), (3, '暂停测试'), (4, '跳过步骤')], default=0),
        ),
    ]
