# Generated by Django 2.0.5 on 2018-06-11 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20180611_0927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['-pk']},
        ),
    ]
