# Generated by Django 2.0.7 on 2019-07-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20190326_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='suiteresult',
            name='error_handle',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
