# Generated by Django 2.0.5 on 2018-06-11 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20180611_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suite',
            old_name='cases',
            new_name='case',
        ),
    ]
