# Generated by Django 2.0.7 on 2019-07-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_suiteresult_error_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='error_handle',
            field=models.IntegerField(choices=[(0, '继承上级'), (1, '中止测试'), (2, '继续测试'), (3, '暂停测试'), (4, '跳过步骤')], default=0),
        ),
        migrations.AlterField(
            model_name='step',
            name='error_handle',
            field=models.IntegerField(choices=[(0, '继承上级'), (1, '中止测试'), (2, '继续测试'), (3, '暂停测试'), (4, '跳过步骤')], default=0),
        ),
    ]
