# Generated by Django 2.0.5 on 2018-06-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20180611_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='suite',
            name='base_timeout',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='suite',
            name='console_log_level',
            field=models.IntegerField(choices=[(0, 'NOTSET'), (10, 'DEBUG'), (20, 'INFO'), (30, 'WARNING'), (40, 'ERROR'), (50, 'CRITICAL')], default=20),
        ),
        migrations.AddField(
            model_name='suite',
            name='log_level',
            field=models.IntegerField(choices=[(0, 'NOTSET'), (10, 'DEBUG'), (20, 'INFO'), (30, 'WARNING'), (40, 'ERROR'), (50, 'CRITICAL')], default=20),
        ),
        migrations.AddField(
            model_name='suite',
            name='thread_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='suite',
            name='ui_get_ss',
            field=models.BooleanField(default=True),
        ),
    ]
