# Generated by Django 2.0.5 on 2018-06-12 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20180611_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('keyword', models.CharField(blank=True, max_length=100)),
                ('variable_group', models.TextField(blank=True)),
                ('level', models.IntegerField(default=1)),
                ('creator', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('execute_count', models.IntegerField(blank=True, null=True)),
                ('pass_count', models.IntegerField(blank=True, null=True)),
                ('fail_count', models.IntegerField(blank=True, null=True)),
                ('error_count', models.IntegerField(blank=True, null=True)),
                ('init_error', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='StepResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('keyword', models.CharField(blank=True, max_length=100)),
                ('variable_group', models.TextField(blank=True)),
                ('action', models.CharField(blank=True, max_length=100)),
                ('timeout', models.FloatField(blank=True, null=True)),
                ('save_as', models.CharField(blank=True, max_length=100)),
                ('ui_by', models.CharField(blank=True, max_length=100)),
                ('ui_locator', models.TextField(blank=True)),
                ('ui_index', models.IntegerField(blank=True, null=True)),
                ('ui_base_element', models.TextField(blank=True)),
                ('ui_data', models.TextField(blank=True)),
                ('ui_special_action', models.CharField(blank=True, max_length=100)),
                ('ui_alert_handle', models.CharField(blank=True, max_length=100)),
                ('api_url', models.TextField(blank=True)),
                ('api_headers', models.TextField(blank=True)),
                ('api_body', models.TextField(blank=True)),
                ('api_data', models.TextField(blank=True)),
                ('creator', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('execute_count', models.IntegerField(blank=True, null=True)),
                ('pass_count', models.IntegerField(blank=True, null=True)),
                ('fail_count', models.IntegerField(blank=True, null=True)),
                ('error_count', models.IntegerField(blank=True, null=True)),
                ('init_error', models.TextField(blank=True)),
                ('case_result', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.CaseResult')),
            ],
        ),
        migrations.CreateModel(
            name='SuiteResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('keyword', models.CharField(blank=True, max_length=100)),
                ('base_timeout', models.FloatField(default=10)),
                ('ui_get_ss', models.BooleanField(default=True)),
                ('thread_count', models.IntegerField(default=1)),
                ('config', models.TextField(blank=True)),
                ('variable_group', models.TextField(blank=True)),
                ('creator', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('execute_count', models.IntegerField(blank=True, null=True)),
                ('pass_count', models.IntegerField(blank=True, null=True)),
                ('fail_count', models.IntegerField(blank=True, null=True)),
                ('error_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='action',
            name='keyword',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='case',
            name='keyword',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='config',
            name='keyword',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='step',
            name='keyword',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='suite',
            name='keyword',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='variablegroup',
            name='keyword',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='suiteresult',
            name='suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Suite'),
        ),
        migrations.AddField(
            model_name='stepresult',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Step'),
        ),
        migrations.AddField(
            model_name='caseresult',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Case'),
        ),
        migrations.AddField(
            model_name='caseresult',
            name='step_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.StepResult'),
        ),
        migrations.AddField(
            model_name='caseresult',
            name='suite_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.SuiteResult'),
        ),
    ]
