# Generated by Django 2.0.5 on 2018-06-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20180612_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseresult',
            name='case_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stepresult',
            name='step_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caseresult',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='config',
            name='ui_selenium_client',
            field=models.IntegerField(choices=[(0, '不启用'), (1, 'Selenium - 本地'), (2, 'Selenium - 远程')], default=0),
        ),
    ]
