# Generated by Django 2.0.5 on 2018-06-12 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20180612_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='ui_remote_id',
            new_name='ui_remote_ip',
        ),
    ]
