# Generated by Django 2.0.5 on 2018-06-13 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20180612_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stepresult',
            name='variable_group',
        ),
    ]
