# Generated by Django 2.0.5 on 2018-06-14 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_remove_stepresult_variable_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseresult',
            name='level',
        ),
        migrations.AddField(
            model_name='caseresult',
            name='parent_case_pk_list',
            field=models.TextField(blank=True),
        ),
    ]
