# Generated by Django 2.0.5 on 2018-06-14 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20180614_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='other_sub_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='step_sub_case', to='main.Case'),
        ),
    ]
