# Generated by Django 2.0.5 on 2018-06-14 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_step_other_sub_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stepresult',
            name='api_body',
        ),
        migrations.RemoveField(
            model_name='stepresult',
            name='api_data',
        ),
        migrations.RemoveField(
            model_name='stepresult',
            name='api_headers',
        ),
        migrations.RemoveField(
            model_name='stepresult',
            name='api_url',
        ),
        migrations.RemoveField(
            model_name='stepresult',
            name='error_count',
        ),
        migrations.RemoveField(
            model_name='stepresult',
            name='execute_count',
        ),
        migrations.RemoveField(
            model_name='stepresult',
            name='fail_count',
        ),
        migrations.RemoveField(
            model_name='stepresult',
            name='init_error',
        ),
        migrations.RemoveField(
            model_name='stepresult',
            name='pass_count',
        ),
        migrations.RemoveField(
            model_name='stepresult',
            name='save_as',
        ),
        migrations.RemoveField(
            model_name='stepresult',
            name='timeout',
        ),
        migrations.RemoveField(
            model_name='stepresult',
            name='ui_alert_handle',
        ),
        migrations.RemoveField(
            model_name='stepresult',
            name='ui_base_element',
        ),
        migrations.RemoveField(
            model_name='stepresult',
            name='ui_by',
        ),
        migrations.RemoveField(
            model_name='stepresult',
            name='ui_data',
        ),
        migrations.RemoveField(
            model_name='stepresult',
            name='ui_index',
        ),
        migrations.RemoveField(
            model_name='stepresult',
            name='ui_locator',
        ),
        migrations.RemoveField(
            model_name='stepresult',
            name='ui_special_action',
        ),
        migrations.AddField(
            model_name='stepresult',
            name='result_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stepresult',
            name='result_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stepresult',
            name='result_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stepresult',
            name='step_snapshot',
            field=models.TextField(blank=True),
        ),
    ]
