# Generated by Django 2.0.5 on 2018-06-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20180614_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseresult',
            name='parent_case_pk_list',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caseresult',
            name='variable_group',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stepresult',
            name='step_snapshot',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suiteresult',
            name='config',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suiteresult',
            name='variable_group',
            field=models.TextField(blank=True, null=True),
        ),
    ]
