# Generated by Django 2.0.5 on 2018-06-19 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0038_suiteresult_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='suiteresult',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='suiteresult',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='suiteresult',
            name='modifier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='suite_result_modifier', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suiteresult',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='suite_result_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
    ]
