# Generated by Django 2.0.5 on 2018-06-20 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20180619_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='img')),
            ],
        ),
        migrations.AddField(
            model_name='stepresult',
            name='screen_shot',
            field=models.ManyToManyField(to='main.ImageStore'),
        ),
    ]
