# Generated by Django 2.0.5 on 2018-06-20 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20180620_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stepresult',
            old_name='screen_shot',
            new_name='screenshots',
        ),
    ]
