# Generated by Django 2.0.5 on 2018-06-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20180620_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='img')),
            ],
        ),
        migrations.AddField(
            model_name='stepresult',
            name='imgs',
            field=models.ManyToManyField(to='main.Image'),
        ),
    ]
