# Generated by Django 2.0.5 on 2018-06-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20180620_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepresult',
            name='has_sub_case',
            field=models.BooleanField(default=False),
        ),
    ]
