# Generated by Django 2.0.5 on 2018-06-26 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_stepresult_has_sub_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suite',
            name='console_log_level',
        ),
    ]
