# Generated by Django 2.0.5 on 2018-06-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_remove_suite_console_log_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepresult',
            name='ui_last_url',
            field=models.TextField(blank=True),
        ),
    ]
