# Generated by Django 2.0.5 on 2018-06-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_stepresult_ui_last_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='other_data',
            field=models.TextField(blank=True),
        ),
    ]
