# Generated by Django 2.0.5 on 2018-06-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_step_other_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='order',
            field=models.FloatField(default=0),
        ),
    ]
