# Generated by Django 2.0.5 on 2018-06-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_action_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='ui_base_element',
            field=models.CharField(max_length=1000),
        ),
    ]
