# Generated by Django 2.0.5 on 2018-06-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_auto_20180627_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='ui_alert_handle',
            field=models.IntegerField(choices=[(1, '确定'), (2, '取消'), (3, '忽略')], default=1),
        ),
        migrations.AlterField(
            model_name='step',
            name='ui_base_element',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
