# Generated by Django 2.0.5 on 2018-06-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_auto_20180627_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='ui_special_action',
            field=models.IntegerField(choices=[(0, ''), (1, '单击'), (2, '点击后不放'), (3, '右键单击'), (4, '双击'), (5, '释放'), (6, '移动偏移量'), (7, '移动到元素'), (8, '移动到元素的相对位置'), (9, '拖动元素到另一元素'), (10, '拖动元素到另一元素的相对位置'), (11, '键盘按下某键不释放'), (12, '键盘释放某键'), (13, '发送按键（组）到当前焦点元素'), (14, '发送按键（组）到指定元素')], default=0),
        ),
    ]
