# Generated by Django 2.0.5 on 2018-06-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_auto_20180628_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='ui_special_action',
            field=models.IntegerField(choices=[(0, ''), (1, '鼠标 - 单击'), (2, '鼠标 - 点击后不放'), (3, '鼠标 - 右键单击'), (4, '鼠标 - 双击'), (5, '鼠标 - 释放'), (6, '鼠标 - 移动偏移量'), (7, '鼠标 - 移动到元素'), (8, '鼠标 - 移动到元素的相对位置'), (9, '鼠标 - 拖动元素到另一元素'), (10, '鼠标 - 拖动元素到另一元素的相对位置'), (11, '键盘 - 按下某键不释放'), (12, '键盘 - 释放某键'), (13, '键盘 - 发送按键（组）到当前焦点元素'), (14, '键盘 - 发送按键（组）到指定元素')], default=0),
        ),
    ]
