# Generated by Django 2.0.5 on 2018-07-02 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_auto_20180702_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suiteresult',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Project'),
        ),
    ]
