# Generated by Django 2.0.5 on 2018-07-02 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_auto_20180702_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suiteresult',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Project'),
            preserve_default=False,
        ),
    ]
