# Generated by Django 2.0.5 on 2018-07-03 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_auto_20180702_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='variablegroup',
            name='project',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Project'),
            preserve_default=False,
        ),
    ]
