# Generated by Django 2.0.5 on 2018-07-03 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_variablegroup_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='variable_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.VariableGroup'),
        ),
    ]
