# Generated by Django 2.0.5 on 2018-07-03 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_auto_20180703_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casevsstep',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Case'),
        ),
        migrations.AlterField(
            model_name='casevsstep',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Step'),
        ),
    ]
