# Generated by Django 2.0.5 on 2018-07-03 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_auto_20180703_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseresult',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Case'),
        ),
        migrations.AlterField(
            model_name='caseresult',
            name='step_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.StepResult'),
        ),
        migrations.AlterField(
            model_name='caseresult',
            name='suite_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SuiteResult'),
        ),
        migrations.AlterField(
            model_name='stepresult',
            name='case_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CaseResult'),
        ),
        migrations.AlterField(
            model_name='stepresult',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Step'),
        ),
        migrations.AlterField(
            model_name='suiteresult',
            name='suite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Suite'),
        ),
        migrations.AlterField(
            model_name='suitevscase',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Case'),
        ),
        migrations.AlterField(
            model_name='suitevscase',
            name='suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Suite'),
        ),
    ]
