# Generated by Django 2.0.5 on 2018-07-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_auto_20180703_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseresult',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='caseresult',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='stepresult',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='stepresult',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='suiteresult',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='suiteresult',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
    ]
