# Generated by Django 2.0.5 on 2018-07-03 08:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_auto_20180703_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid1, editable=False, primary_key=True, serialize=False),
        ),
    ]
