# Generated by Django 2.0.5 on 2018-07-04 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_auto_20180703_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['-modified_date']},
        ),
        migrations.AlterModelOptions(
            name='casevsstep',
            options={'ordering': ['-modified_date']},
        ),
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['-modified_date']},
        ),
        migrations.AlterModelOptions(
            name='suitevscase',
            options={'ordering': ['-modified_date']},
        ),
        migrations.AddField(
            model_name='action',
            name='code',
            field=models.UUIDField(auto_created=True, default=uuid.uuid1, editable=False),
        ),
        migrations.AddField(
            model_name='actiontype',
            name='code',
            field=models.UUIDField(auto_created=True, default=uuid.uuid1, editable=False),
        ),
        migrations.AddField(
            model_name='case',
            name='code',
            field=models.UUIDField(auto_created=True, default=uuid.uuid1, editable=False),
        ),
        migrations.AddField(
            model_name='caseresult',
            name='code',
            field=models.UUIDField(auto_created=True, default=uuid.uuid1, editable=False),
        ),
        migrations.AddField(
            model_name='config',
            name='code',
            field=models.UUIDField(auto_created=True, default=uuid.uuid1, editable=False),
        ),
        migrations.AddField(
            model_name='image',
            name='code',
            field=models.UUIDField(auto_created=True, default=uuid.uuid1, editable=False),
        ),
        migrations.AddField(
            model_name='project',
            name='code',
            field=models.UUIDField(auto_created=True, default=uuid.uuid1, editable=False),
        ),
        migrations.AddField(
            model_name='step',
            name='code',
            field=models.UUIDField(auto_created=True, default=uuid.uuid1, editable=False),
        ),
        migrations.AddField(
            model_name='stepresult',
            name='code',
            field=models.UUIDField(auto_created=True, default=uuid.uuid1, editable=False),
        ),
        migrations.AddField(
            model_name='suite',
            name='code',
            field=models.UUIDField(auto_created=True, default=uuid.uuid1, editable=False),
        ),
        migrations.AddField(
            model_name='suiteresult',
            name='code',
            field=models.UUIDField(auto_created=True, default=uuid.uuid1, editable=False),
        ),
        migrations.AddField(
            model_name='variable',
            name='code',
            field=models.UUIDField(auto_created=True, default=uuid.uuid1, editable=False),
        ),
        migrations.AddField(
            model_name='variablegroup',
            name='code',
            field=models.UUIDField(auto_created=True, default=uuid.uuid1, editable=False),
        ),
        migrations.AlterField(
            model_name='action',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='action',
            name='modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_modifier', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ActionType'),
        ),
        migrations.AlterField(
            model_name='case',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='case',
            name='modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_modifier', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='case',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Project'),
        ),
        migrations.AlterField(
            model_name='case',
            name='variable_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.VariableGroup'),
        ),
        migrations.AlterField(
            model_name='caseresult',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='casevsstep',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_vs_step_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='casevsstep',
            name='modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_vs_step_modifier', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='config',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='config',
            name='modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_modifier', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='step',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Action'),
        ),
        migrations.AlterField(
            model_name='step',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='step_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='step',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='step',
            name='modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='step_modifier', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='step',
            name='other_sub_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='step_sub_case', to='main.Case'),
        ),
        migrations.AlterField(
            model_name='step',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Project'),
        ),
        migrations.AlterField(
            model_name='stepresult',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='suite',
            name='config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Config'),
        ),
        migrations.AlterField(
            model_name='suite',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suite_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='suite',
            name='modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suite_modifier', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='suite',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Project'),
        ),
        migrations.AlterField(
            model_name='suite',
            name='variable_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.VariableGroup'),
        ),
        migrations.AlterField(
            model_name='suiteresult',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suite_result_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='suiteresult',
            name='modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suite_result_modifier', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='suiteresult',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Project'),
        ),
        migrations.AlterField(
            model_name='suitevscase',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suite_vs_case_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='suitevscase',
            name='modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suite_vs_case_modifier', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='variablegroup',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variable_group_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='variablegroup',
            name='modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variable_group_modifier', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='variablegroup',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Project'),
        ),
    ]
