# Generated by Django 2.0.5 on 2018-07-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_auto_20180705_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suite',
            name='log_level',
            field=models.IntegerField(choices=[(1, 'DEV'), (10, 'DEBUG'), (20, 'INFO'), (30, 'WARNING'), (40, 'ERROR'), (50, 'CRITICAL')], default=20),
        ),
    ]
