# Generated by Django 2.0.5 on 2018-08-01 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_auto_20180711_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'ordering': ['-modified_date']},
        ),
        migrations.AlterModelOptions(
            name='suite',
            options={'ordering': ['-modified_date']},
        ),
        migrations.AlterModelOptions(
            name='suiteresult',
            options={'ordering': ['-modified_date']},
        ),
        migrations.AlterModelOptions(
            name='variablegroup',
            options={'ordering': ['-modified_date']},
        ),
        migrations.RenameField(
            model_name='stepresult',
            old_name='step_snapshot',
            new_name='snapshot',
        ),
    ]
