# Generated by Django 2.0.5 on 2018-08-03 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_auto_20180801_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suite',
            old_name='base_timeout',
            new_name='timeout',
        ),
        migrations.RenameField(
            model_name='suiteresult',
            old_name='base_timeout',
            new_name='timeout',
        ),
    ]
