# Generated by Django 2.0.5 on 2018-08-08 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_auto_20180803_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='code',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='actiontype',
            old_name='code',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='code',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='caseresult',
            old_name='code',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='config',
            old_name='code',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='code',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='code',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='step',
            old_name='code',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='stepresult',
            old_name='code',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='suite',
            old_name='code',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='suiteresult',
            old_name='code',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='variable',
            old_name='code',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='variablegroup',
            old_name='code',
            new_name='uuid',
        ),
    ]
