# Generated by Django 2.0.5 on 2018-08-08 11:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_auto_20180808_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid1, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='actiontype',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid1, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid1, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='caseresult',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid1, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid1, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid1, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid1, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid1, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='stepresult',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid1, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='suite',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid1, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='suiteresult',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid1, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid1, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='variablegroup',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid1, editable=False, unique=True),
        ),
    ]
