# Generated by Django 2.0.5 on 2018-08-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_auto_20180808_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='code',
            field=models.CharField(default='a', max_length=100),
        ),
    ]
