# Generated by Django 2.0.5 on 2018-08-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_action_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
