# Generated by Django 2.0.5 on 2018-08-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_auto_20180808_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiontype',
            name='code',
            field=models.CharField(default='a', max_length=100),
        ),
    ]
