# Generated by Django 2.0.5 on 2018-08-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_actiontype_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiontype',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
